// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: chat/v1/chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	ChatType_PRIVATE ChatType = 0
	ChatType_GROUP   ChatType = 1
	ChatType_CHANNEL ChatType = 2
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "PRIVATE",
		1: "GROUP",
		2: "CHANNEL",
	}
	ChatType_value = map[string]int32{
		"PRIVATE": 0,
		"GROUP":   1,
		"CHANNEL": 2,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_chat_v1_chat_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

type MemberRole int32

const (
	MemberRole_MEMBER MemberRole = 0
	MemberRole_ADMIN  MemberRole = 1
	MemberRole_OWNER  MemberRole = 2
)

// Enum value maps for MemberRole.
var (
	MemberRole_name = map[int32]string{
		0: "MEMBER",
		1: "ADMIN",
		2: "OWNER",
	}
	MemberRole_value = map[string]int32{
		"MEMBER": 0,
		"ADMIN":  1,
		"OWNER":  2,
	}
)

func (x MemberRole) Enum() *MemberRole {
	p := new(MemberRole)
	*p = x
	return p
}

func (x MemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_v1_chat_proto_enumTypes[1].Descriptor()
}

func (MemberRole) Type() protoreflect.EnumType {
	return &file_chat_v1_chat_proto_enumTypes[1]
}

func (x MemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberRole.Descriptor instead.
func (MemberRole) EnumDescriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          ChatType               `protobuf:"varint,4,opt,name=type,proto3,enum=chat.ChatType" json:"type,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	InviteCode    string                 `protobuf:"bytes,6,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MemberCount   int32                  `protobuf:"varint,10,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Chat) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_PRIVATE
}

func (x *Chat) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Chat) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *Chat) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Chat) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Chat) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Chat) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type ChatMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          MemberRole             `protobuf:"varint,3,opt,name=role,proto3,enum=chat.MemberRole" json:"role,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMember) Reset() {
	*x = ChatMember{}
	mi := &file_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMember) ProtoMessage() {}

func (x *ChatMember) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMember.ProtoReflect.Descriptor instead.
func (*ChatMember) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMember) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMember) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER
}

func (x *ChatMember) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          ChatType               `protobuf:"varint,3,opt,name=type,proto3,enum=chat.ChatType" json:"type,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	MemberIds     []string               `protobuf:"bytes,5,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateChatRequest) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_PRIVATE
}

func (x *CreateChatRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateChatRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GetChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type UpdateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	RequesterId   string                 `protobuf:"bytes,5,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatRequest) Reset() {
	*x = UpdateChatRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRequest) ProtoMessage() {}

func (x *UpdateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChatRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateChatRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateChatRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type UpdateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatResponse) Reset() {
	*x = UpdateChatResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatResponse) ProtoMessage() {}

func (x *UpdateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *DeleteChatRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type DeleteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatResponse) Reset() {
	*x = DeleteChatResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatResponse) ProtoMessage() {}

func (x *DeleteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *AddMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMemberRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *ChatMember            `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *AddMemberResponse) GetMember() *ChatMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveMemberRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetChatMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMembersRequest) Reset() {
	*x = GetChatMembersRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMembersRequest) ProtoMessage() {}

func (x *GetChatMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMembersRequest.ProtoReflect.Descriptor instead.
func (*GetChatMembersRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *GetChatMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetChatMembersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetChatMembersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetChatMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ChatMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMembersResponse) Reset() {
	*x = GetChatMembersResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMembersResponse) ProtoMessage() {}

func (x *GetChatMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMembersResponse.ProtoReflect.Descriptor instead.
func (*GetChatMembersResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *GetChatMembersResponse) GetMembers() []*ChatMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetChatMembersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListUserChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{16}
}

func (x *ListUserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserChatsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserChatsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{17}
}

func (x *ListUserChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ListUserChatsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LeaveChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatRequest) Reset() {
	*x = LeaveChatRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatRequest) ProtoMessage() {}

func (x *LeaveChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatRequest.ProtoReflect.Descriptor instead.
func (*LeaveChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{18}
}

func (x *LeaveChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *LeaveChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatResponse) Reset() {
	*x = LeaveChatResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatResponse) ProtoMessage() {}

func (x *LeaveChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatResponse.ProtoReflect.Descriptor instead.
func (*LeaveChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{19}
}

func (x *LeaveChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MakeAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAdminRequest) Reset() {
	*x = MakeAdminRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminRequest) ProtoMessage() {}

func (x *MakeAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminRequest.ProtoReflect.Descriptor instead.
func (*MakeAdminRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{20}
}

func (x *MakeAdminRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MakeAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MakeAdminRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type MakeAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *ChatMember            `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAdminResponse) Reset() {
	*x = MakeAdminResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminResponse) ProtoMessage() {}

func (x *MakeAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminResponse.ProtoReflect.Descriptor instead.
func (*MakeAdminResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{21}
}

func (x *MakeAdminResponse) GetMember() *ChatMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type SearchChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsRequest) Reset() {
	*x = SearchChatsRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsRequest) ProtoMessage() {}

func (x *SearchChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsRequest.ProtoReflect.Descriptor instead.
func (*SearchChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{22}
}

func (x *SearchChatsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsResponse) Reset() {
	*x = SearchChatsResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsResponse) ProtoMessage() {}

func (x *SearchChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsResponse.ProtoReflect.Descriptor instead.
func (*SearchChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{23}
}

func (x *SearchChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type UpdateChatSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsMuted       bool                   `protobuf:"varint,3,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsPinned      bool                   `protobuf:"varint,4,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatSettingsRequest) Reset() {
	*x = UpdateChatSettingsRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatSettingsRequest) ProtoMessage() {}

func (x *UpdateChatSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateChatSettingsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateChatSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateChatSettingsRequest) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *UpdateChatSettingsRequest) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

type UpdateChatSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatSettingsResponse) Reset() {
	*x = UpdateChatSettingsResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatSettingsResponse) ProtoMessage() {}

func (x *UpdateChatSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatSettingsResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateChatSettingsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_chat_v1_chat_proto protoreflect.FileDescriptor

const file_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x12chat/v1/chat.proto\x12\x04chat\"\xa9\x02\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0e.chat.ChatTypeR\x04type\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vinvite_code\x18\x06 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12!\n" +
	"\fmember_count\x18\n" +
	" \x01(\x05R\vmemberCount\"\x81\x01\n" +
	"\n" +
	"ChatMember\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x04role\x18\x03 \x01(\x0e2\x10.chat.MemberRoleR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x04 \x01(\tR\bjoinedAt\"\xab\x01\n" +
	"\x11CreateChatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0e.chat.ChatTypeR\x04type\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\tR\tmemberIds\"4\n" +
	"\x12CreateChatResponse\x12\x1e\n" +
	"\x04chat\x18\x01 \x01(\v2\n" +
	".chat.ChatR\x04chat\")\n" +
	"\x0eGetChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"1\n" +
	"\x0fGetChatResponse\x12\x1e\n" +
	"\x04chat\x18\x01 \x01(\v2\n" +
	".chat.ChatR\x04chat\"\x9d\x01\n" +
	"\x11UpdateChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12!\n" +
	"\frequester_id\x18\x05 \x01(\tR\vrequesterId\"4\n" +
	"\x12UpdateChatResponse\x12\x1e\n" +
	"\x04chat\x18\x01 \x01(\v2\n" +
	".chat.ChatR\x04chat\"O\n" +
	"\x11DeleteChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\".\n" +
	"\x12DeleteChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x10AddMemberRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\"=\n" +
	"\x11AddMemberResponse\x12(\n" +
	"\x06member\x18\x01 \x01(\v2\x10.chat.ChatMemberR\x06member\"j\n" +
	"\x13RemoveMemberRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\"0\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x15GetChatMembersRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"Z\n" +
	"\x16GetChatMembersResponse\x12*\n" +
	"\amembers\x18\x01 \x03(\v2\x10.chat.ChatMemberR\amembers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"^\n" +
	"\x14ListUserChatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"O\n" +
	"\x15ListUserChatsResponse\x12 \n" +
	"\x05chats\x18\x01 \x03(\v2\n" +
	".chat.ChatR\x05chats\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"D\n" +
	"\x10LeaveChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x11LeaveChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x10MakeAdminRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\"=\n" +
	"\x11MakeAdminResponse\x12(\n" +
	"\x06member\x18\x01 \x01(\v2\x10.chat.ChatMemberR\x06member\"Y\n" +
	"\x12SearchChatsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"7\n" +
	"\x13SearchChatsResponse\x12 \n" +
	"\x05chats\x18\x01 \x03(\v2\n" +
	".chat.ChatR\x05chats\"\x85\x01\n" +
	"\x19UpdateChatSettingsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bis_muted\x18\x03 \x01(\bR\aisMuted\x12\x1b\n" +
	"\tis_pinned\x18\x04 \x01(\bR\bisPinned\"6\n" +
	"\x1aUpdateChatSettingsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*/\n" +
	"\bChatType\x12\v\n" +
	"\aPRIVATE\x10\x00\x12\t\n" +
	"\x05GROUP\x10\x01\x12\v\n" +
	"\aCHANNEL\x10\x02*.\n" +
	"\n" +
	"MemberRole\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\t\n" +
	"\x05OWNER\x10\x022\xbd\x06\n" +
	"\vChatService\x12?\n" +
	"\n" +
	"CreateChat\x12\x17.chat.CreateChatRequest\x1a\x18.chat.CreateChatResponse\x126\n" +
	"\aGetChat\x12\x14.chat.GetChatRequest\x1a\x15.chat.GetChatResponse\x12?\n" +
	"\n" +
	"UpdateChat\x12\x17.chat.UpdateChatRequest\x1a\x18.chat.UpdateChatResponse\x12?\n" +
	"\n" +
	"DeleteChat\x12\x17.chat.DeleteChatRequest\x1a\x18.chat.DeleteChatResponse\x12<\n" +
	"\tAddMember\x12\x16.chat.AddMemberRequest\x1a\x17.chat.AddMemberResponse\x12E\n" +
	"\fRemoveMember\x12\x19.chat.RemoveMemberRequest\x1a\x1a.chat.RemoveMemberResponse\x12K\n" +
	"\x0eGetChatMembers\x12\x1b.chat.GetChatMembersRequest\x1a\x1c.chat.GetChatMembersResponse\x12H\n" +
	"\rListUserChats\x12\x1a.chat.ListUserChatsRequest\x1a\x1b.chat.ListUserChatsResponse\x12<\n" +
	"\tLeaveChat\x12\x16.chat.LeaveChatRequest\x1a\x17.chat.LeaveChatResponse\x12<\n" +
	"\tMakeAdmin\x12\x16.chat.MakeAdminRequest\x1a\x17.chat.MakeAdminResponse\x12B\n" +
	"\vSearchChats\x12\x18.chat.SearchChatsRequest\x1a\x19.chat.SearchChatsResponse\x12W\n" +
	"\x12UpdateChatSettings\x12\x1f.chat.UpdateChatSettingsRequest\x1a .chat.UpdateChatSettingsResponseBMZKgithub.com/Order-Payment-Go-Microservice/proto-genertion/gen/chat/v1;chatv1b\x06proto3"

var (
	file_chat_v1_chat_proto_rawDescOnce sync.Once
	file_chat_v1_chat_proto_rawDescData []byte
)

func file_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_v1_chat_proto_rawDesc), len(file_chat_v1_chat_proto_rawDesc)))
	})
	return file_chat_v1_chat_proto_rawDescData
}

var file_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_chat_v1_chat_proto_goTypes = []any{
	(ChatType)(0),                      // 0: chat.ChatType
	(MemberRole)(0),                    // 1: chat.MemberRole
	(*Chat)(nil),                       // 2: chat.Chat
	(*ChatMember)(nil),                 // 3: chat.ChatMember
	(*CreateChatRequest)(nil),          // 4: chat.CreateChatRequest
	(*CreateChatResponse)(nil),         // 5: chat.CreateChatResponse
	(*GetChatRequest)(nil),             // 6: chat.GetChatRequest
	(*GetChatResponse)(nil),            // 7: chat.GetChatResponse
	(*UpdateChatRequest)(nil),          // 8: chat.UpdateChatRequest
	(*UpdateChatResponse)(nil),         // 9: chat.UpdateChatResponse
	(*DeleteChatRequest)(nil),          // 10: chat.DeleteChatRequest
	(*DeleteChatResponse)(nil),         // 11: chat.DeleteChatResponse
	(*AddMemberRequest)(nil),           // 12: chat.AddMemberRequest
	(*AddMemberResponse)(nil),          // 13: chat.AddMemberResponse
	(*RemoveMemberRequest)(nil),        // 14: chat.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),       // 15: chat.RemoveMemberResponse
	(*GetChatMembersRequest)(nil),      // 16: chat.GetChatMembersRequest
	(*GetChatMembersResponse)(nil),     // 17: chat.GetChatMembersResponse
	(*ListUserChatsRequest)(nil),       // 18: chat.ListUserChatsRequest
	(*ListUserChatsResponse)(nil),      // 19: chat.ListUserChatsResponse
	(*LeaveChatRequest)(nil),           // 20: chat.LeaveChatRequest
	(*LeaveChatResponse)(nil),          // 21: chat.LeaveChatResponse
	(*MakeAdminRequest)(nil),           // 22: chat.MakeAdminRequest
	(*MakeAdminResponse)(nil),          // 23: chat.MakeAdminResponse
	(*SearchChatsRequest)(nil),         // 24: chat.SearchChatsRequest
	(*SearchChatsResponse)(nil),        // 25: chat.SearchChatsResponse
	(*UpdateChatSettingsRequest)(nil),  // 26: chat.UpdateChatSettingsRequest
	(*UpdateChatSettingsResponse)(nil), // 27: chat.UpdateChatSettingsResponse
}
var file_chat_v1_chat_proto_depIdxs = []int32{
	0,  // 0: chat.Chat.type:type_name -> chat.ChatType
	1,  // 1: chat.ChatMember.role:type_name -> chat.MemberRole
	0,  // 2: chat.CreateChatRequest.type:type_name -> chat.ChatType
	2,  // 3: chat.CreateChatResponse.chat:type_name -> chat.Chat
	2,  // 4: chat.GetChatResponse.chat:type_name -> chat.Chat
	2,  // 5: chat.UpdateChatResponse.chat:type_name -> chat.Chat
	3,  // 6: chat.AddMemberResponse.member:type_name -> chat.ChatMember
	3,  // 7: chat.GetChatMembersResponse.members:type_name -> chat.ChatMember
	2,  // 8: chat.ListUserChatsResponse.chats:type_name -> chat.Chat
	3,  // 9: chat.MakeAdminResponse.member:type_name -> chat.ChatMember
	2,  // 10: chat.SearchChatsResponse.chats:type_name -> chat.Chat
	4,  // 11: chat.ChatService.CreateChat:input_type -> chat.CreateChatRequest
	6,  // 12: chat.ChatService.GetChat:input_type -> chat.GetChatRequest
	8,  // 13: chat.ChatService.UpdateChat:input_type -> chat.UpdateChatRequest
	10, // 14: chat.ChatService.DeleteChat:input_type -> chat.DeleteChatRequest
	12, // 15: chat.ChatService.AddMember:input_type -> chat.AddMemberRequest
	14, // 16: chat.ChatService.RemoveMember:input_type -> chat.RemoveMemberRequest
	16, // 17: chat.ChatService.GetChatMembers:input_type -> chat.GetChatMembersRequest
	18, // 18: chat.ChatService.ListUserChats:input_type -> chat.ListUserChatsRequest
	20, // 19: chat.ChatService.LeaveChat:input_type -> chat.LeaveChatRequest
	22, // 20: chat.ChatService.MakeAdmin:input_type -> chat.MakeAdminRequest
	24, // 21: chat.ChatService.SearchChats:input_type -> chat.SearchChatsRequest
	26, // 22: chat.ChatService.UpdateChatSettings:input_type -> chat.UpdateChatSettingsRequest
	5,  // 23: chat.ChatService.CreateChat:output_type -> chat.CreateChatResponse
	7,  // 24: chat.ChatService.GetChat:output_type -> chat.GetChatResponse
	9,  // 25: chat.ChatService.UpdateChat:output_type -> chat.UpdateChatResponse
	11, // 26: chat.ChatService.DeleteChat:output_type -> chat.DeleteChatResponse
	13, // 27: chat.ChatService.AddMember:output_type -> chat.AddMemberResponse
	15, // 28: chat.ChatService.RemoveMember:output_type -> chat.RemoveMemberResponse
	17, // 29: chat.ChatService.GetChatMembers:output_type -> chat.GetChatMembersResponse
	19, // 30: chat.ChatService.ListUserChats:output_type -> chat.ListUserChatsResponse
	21, // 31: chat.ChatService.LeaveChat:output_type -> chat.LeaveChatResponse
	23, // 32: chat.ChatService.MakeAdmin:output_type -> chat.MakeAdminResponse
	25, // 33: chat.ChatService.SearchChats:output_type -> chat.SearchChatsResponse
	27, // 34: chat.ChatService.UpdateChatSettings:output_type -> chat.UpdateChatSettingsResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_chat_v1_chat_proto_init() }
func file_chat_v1_chat_proto_init() {
	if File_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_v1_chat_proto_rawDesc), len(file_chat_v1_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_chat_v1_chat_proto = out.File
	file_chat_v1_chat_proto_goTypes = nil
	file_chat_v1_chat_proto_depIdxs = nil
}
